#!/usr/bin/env python3
"""Manifest-driven MassMotionConsole batch runner template.

Use this with manifests generated by create_massmotion_console_manifest.py.
Each row is executed as an independent MassMotionConsole command and the result
CSV is updated after every run.
"""

from __future__ import annotations

import argparse
import csv
import shlex
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


def read_manifest(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as file:
        return list(csv.DictReader(file))


def write_results(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def command_from_row(row: dict[str, str]) -> list[str]:
    if row.get("command"):
        return shlex.split(row["command"])
    command = [row["console_path"], "--project", row["project_path"]]
    if row.get("scriptfile_path"):
        command.extend(["--scriptfile", row["scriptfile_path"]])
    if row.get("scriptobject"):
        command.extend(["--scriptobject", row["scriptobject"]])
    if row.get("simulation_path"):
        command.extend(["--simulation", row["simulation_path"]])
    if row.get("seed"):
        command.extend(["--seed", row["seed"]])
    if row.get("threads"):
        command.extend(["--threads", row["threads"]])
    if row.get("query_names") == "ALL":
        command.append("--queryall")
    elif row.get("query_names"):
        for query in row["query_names"].split("|"):
            if query:
                command.extend(["--query", query])
    return command


def run_row(row: dict[str, str], args: argparse.Namespace) -> dict[str, Any]:
    output_dir = Path(row.get("output_dir") or "results")
    output_dir.mkdir(parents=True, exist_ok=True)
    command = command_from_row(row)
    result_row: dict[str, Any] = dict(row)
    started = time.perf_counter()

    if args.dry_run:
        result_row.update(
            {
                "completed": True,
                "returncode": 0,
                "elapsed_wall_seconds": 0,
                "stdout_tail": "",
                "stderr_tail": "",
                "error": "",
            }
        )
        return result_row

    try:
        completed = subprocess.run(
            command,
            cwd=args.cwd,
            text=True,
            capture_output=True,
            timeout=args.timeout,
            check=False,
        )
        elapsed = time.perf_counter() - started
        result_row.update(
            {
                "completed": completed.returncode == 0,
                "returncode": completed.returncode,
                "elapsed_wall_seconds": round(elapsed, 3),
                "stdout_tail": completed.stdout[-2000:],
                "stderr_tail": completed.stderr[-2000:],
                "error": "",
            }
        )
    except Exception as exc:
        elapsed = time.perf_counter() - started
        result_row.update(
            {
                "completed": False,
                "returncode": "",
                "elapsed_wall_seconds": round(elapsed, 3),
                "stdout_tail": "",
                "stderr_tail": "",
                "error": str(exc),
            }
        )
    return result_row


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run MassMotionConsole commands from a manifest.")
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path("results") / "massmotion_console_results.csv")
    parser.add_argument("--cwd", type=Path, help="working directory for MassMotionConsole")
    parser.add_argument("--timeout", type=float, default=None, help="seconds per run")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--stop-on-error", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = read_manifest(args.manifest)
    results: list[dict[str, Any]] = []
    for row in rows:
        result = run_row(row, args)
        results.append(result)
        write_results(args.out, results)
        if args.stop_on_error and not result.get("completed"):
            break
    print(f"Wrote {len(results)} MassMotionConsole result rows to {args.out}")
    return 0 if all(row.get("completed") for row in results) else 1


if __name__ == "__main__":
    sys.exit(main())
